apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraform-cloud-token
  namespace: tcmetrics
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: lighthouse-secrets
    kind: ClusterSecretStore
  target:
    name: terraform-cloud-token
  data:
    - secretKey: TFE_TOKEN
      remoteRef:
        key: arn:aws:secretsmanager:eu-west-1:606127501664:secret:terraform-cloud-metrics-token-ewJx78
